DOMAIN = "glow_dcc_backfill"

CONF_EMAIL = "email"
CONF_PASSWORD = "password"
CONF_RESOURCE_ID = "resource_id"

CONF_TARIFF_COUNT = "tariff_count"
CONF_API_RATE = "api_rate"

CONF_CHEAP_RATE = "cheap_rate"
CONF_STANDARD_RATE = "standard_rate"
CONF_PEAK_RATE = "peak_rate"

CONF_CHEAP_START = "cheap_start"
CONF_CHEAP_END = "cheap_end"
CONF_PEAK_START = "peak_start"
CONF_PEAK_END = "peak_end"

TARIFF_COUNT_SINGLE = "1"
TARIFF_COUNT_TWO = "2"
TARIFF_COUNT_THREE = "3"

DEFAULT_TARIFF_COUNT = TARIFF_COUNT_SINGLE

DEFAULT_CHEAP_RATE = 0.1372
DEFAULT_STANDARD_RATE = 0.2081
DEFAULT_PEAK_RATE = 0.3874

DEFAULT_CHEAP_START = "02:00"
DEFAULT_CHEAP_END = "05:00"
DEFAULT_PEAK_START = "16:00"
DEFAULT_PEAK_END = "19:00"